apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - name: ftps
      port: 21
      targetPort: 21
      protocol: TCP
    - name: data0
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: data1
      port: 30001
      targetPort: 30001
      protocol: TCP
    - name: data2
      port: 30002
      targetPort: 30002
      protocol: TCP
    - name: data3
      port: 30003
      targetPort: 30003
      protocol: TCP
    - name: data4
      port: 30004
      targetPort: 30004
      protocol: TCP
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        ports:
        - containerPort: 21
          name: ftps
        imagePullPolicy: Never
