apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: "mysql"
        imagePullPolicy: Never
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim